-- Vehicles
-- add any custom vehicles here
-- we dont include motorcycles here, i suggest you not
Config.Vehicles = {
	skyline = {
		category = "sports",
		brand = "Nissan",
		model = "skyline",
		price = 30000,
		name = "Nissan Skyline R34 Gtr",
	  },
	cyclone = {
	   category = "super",
	   brand = "Coil",
	   model = "cyclone",
	   price = 30000,
	   name = "Cyclone",
	 },
	schlagen = {
	   category = "sports",
	   brand = "Benefactor",
	   model = "schlagen",
	   price = 16000,
	   name = "Schlagen GT",
	 },
	slamvan = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "slamvan",
	   price = 3000,
	   name = "Slam Van",
	 },
	vstr = {
	   category = "sports",
	   brand = "Albany",
	   model = "vstr",
	   price = 8000,
	   name = "V-STR",
	 },
	slamtruck = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "slamtruck",
	   price = 10000,
	   name = "Slam Truck",
	 },
	minivan2 = {
	   category = "vans",
	   brand = "Vapid",
	   model = "minivan2",
	   price = 1000,
	   name = "Minivan Custom",
	 },
	jb700 = {
	   category = "sportsclassic",
	   brand = "Dewbauchee",
	   model = "jb700",
	   price = 24000,
	   name = "JB 700",
	 },
	voltic = {
	   category = "super",
	   brand = "Coil",
	   model = "voltic",
	   price = 12000,
	   name = "Voltic",
	 },
	rhapsody = {
	   category = "compacts",
	   brand = "Declasse",
	   model = "rhapsody",
	   price = 1000,
	   name = "Rhapsody",
	 },
	sultan2 = {
	   category = "sports",
	   brand = "Karin",
	   model = "sultan2",
	   price = 5500,
	   name = "Sultan Custom",
	 },
	cavalcade2 = {
	   category = "suvs",
	   brand = "Albany",
	   model = "cavalcade2",
	   price = 1650,
	   name = "Cavalcade",
	 },
	paragon = {
	   category = "sports",
	   brand = "Enus",
	   model = "paragon",
	   price = 6000,
	   name = "Paragon",
	 },
	sandking = {
	   category = "offroad",
	   brand = "Annis",
	   model = "sandking",
	   price = 2500,
	   name = "Sandking",
	 },
	ninef2 = {
	   category = "sports",
	   brand = "Obey",
	   model = "ninef2",
	   price = 10500,
	   name = "9F Cabrio",
	 },
	nero2 = {
	   category = "super",
	   brand = "Truffade",
	   model = "nero2",
	   price = 26000,
	   name = "Nero Custom",
	 },
	khamelion = {
	   category = "sports",
	   brand = "Hijak",
	   model = "khamelion",
	   price = 9000,
	   name = "Khamelion",
	 },
	mesa3 = {
	   category = "offroad",
	   brand = "Canis",
	   model = "mesa3",
	   price = 40000,
	   name = "Mesa Merryweather",
	 },
	blazer4 = {
	   category = "offroad",
	   brand = "Annis",
	   model = "blazer4",
	   price = 925,
	   name = "Blazer Sport",
	 },
	flashgt = {
	   category = "sports",
	   brand = "Vapid",
	   model = "flashgt",
	   price = 4800,
	   name = "Flash GT",
	 },
	z190 = {
	   category = "sportsclassics",
	   brand = "Karin",
	   model = "z190",
	   price = 7800,
	   name = "190Z",
	 },
	prairie = {
	   category = "compacts",
	   brand = "Bollokan",
	   model = "prairie",
	   price = 3000,
	   name = "Prairie",
	 },
	ninef = {
	   category = "sports",
	   brand = "Obey",
	   model = "ninef",
	   price = 9500,
	   name = "9F",
	 },
	tornado = {
	   category = "sportsclassic",
	   brand = "Declasse",
	   model = "tornado",
	   price = 2100,
	   name = "Tornado",
	 },
	tigon = {
	   category = "super",
	   brand = "Lampadati",
	   model = "tigon",
	   price = 24000,
	   name = "Tigon",
	 },
	vacca = {
	   category = "super",
	   brand = "Pegassi",
	   model = "vacca",
	   price = 10500,
	   name = "Vacca",
	 },
	tyrant = {
	   category = "super",
	   brand = " Överflöd",
	   model = "tyrant",
	   price = 210000,
	   name = "Tyrant",
	 },
	comet2 = {
	   category = "sports",
	   brand = "Pfister",
	   model = "comet2",
	   price = 13000,
	   name = "Comet",
	 },
	dilettante = {
	   category = "compacts",
	   brand = "Karin",
	   model = "dilettante",
	   price = 900,
	   name = "Dilettante",
	 },
	jester4 = {
	   category = "sports",
	   brand = "Dinka",
	   model = "jester4",
	   price = 24000,
	   name = "Jester RR",
	 },
	jackal = {
	   category = "coupes",
	   brand = "Ocelot",
	   model = "jackal",
	   price = 1900,
	   name = "Jackal",
	 },
	warrener = {
	   category = "sedans",
	   brand = "Vulcar",
	   model = "warrener",
	   price = 400,
	   name = "Warrener",
	 },
	tempesta = {
	   category = "super",
	   brand = "Pegassi",
	   model = "tempesta",
	   price = 12000,
	   name = "Tempesta",
	 },
	dukes2 = {
	   category = "muscle",
	   brand = "Imponte",
	   model = "dukes2",
	   price = 6000,
	   name = "Dukes Nightrider",
	 },
	sentinel2 = {
	   category = "coupes",
	   brand = " Übermacht",
	   model = "sentinel2",
	   price = 3300,
	   name = "Sentinel XS",
	 },
	coquette = {
	   category = "sports",
	   brand = "Invetero",
	   model = "coquette",
	   price = 14500,
	   name = "Coquette",
	 },
	zion = {
	   category = "coupes",
	   brand = "Übermacht",
	   model = "zion",
	   price = 2200,
	   name = "Zion",
	 },
	faction2 = {
	   category = "muscle",
	   brand = "Willard",
	   model = "faction2",
	   price = 1900,
	   name = "Faction Rider",
	 },
	dubsta3 = {
	   category = "offroad",
	   brand = "Annis",
	   model = "dubsta3",
	   price = 3400,
	   name = "Dubsta 6x6",
	 },
	buffalo2 = {
	   category = "sports",
	   brand = "Bravado",
	   model = "buffalo2",
	   price = 2450,
	   name = "Buffalo S",
	 },
	journey = {
	   category = "vans",
	   brand = "Zirconium",
	   model = "journey",
	   price = 650,
	   name = "Journey",
	 },
	caracara = {
	   category = "offroad",
	   brand = "Vapid",
	   model = "caracara",
	   price = 6000,
	   name = "Caracara",
	 },
	baller = {
	   category = "suvs",
	   brand = "Gallivanter",
	   model = "baller",
	   price = 2200,
	   name = "Baller",
	 },
	peyote2 = {
	   category = "sportsclassic",
	   brand = "Vapid",
	   model = "peyote2",
	   price = 4000,
	   name = "Peyote Gasser",
	 },
	sadler = {
	   category = "offroad",
	   brand = "Vapid",
	   model = "sadler",
	   price = 2000,
	   name = "Sadler",
	 },
	neo = {
	   category = "sports",
	   brand = "Vysser",
	   model = "neo",
	   price = 23000,
	   name = "Neo",
	 },
	sandking2 = {
	   category = "offroad",
	   brand = "Annis",
	   model = "sandking2",
	   price = 3800,
	   name = "Sandking SWB",
	 },
	cogcabrio = {
	   category = "coupes",
	   brand = "Enus",
	   model = "cogcabrio",
	   price = 3000,
	   name = "Cognoscenti Cabrio",
	 },
	speedo = {
	   category = "vans",
	   brand = "Vapid",
	   model = "speedo",
	   price = 1000,
	   name = "Speedo",
	 },
	coquette3 = {
	   category = "muscle",
	   brand = "Invetero",
	   model = "coquette3",
	   price = 18000,
	   name = "Coquette BlackFin",
	 },
	zentorno = {
	   category = "super",
	   brand = "Pegassi",
	   model = "zentorno",
	   price = 34000,
	   name = "Zentorno",
	 },
	baller3 = {
	   category = "suvs",
	   brand = "Gallivanter",
	   model = "baller3",
	   price = 1500,
	   name = "Baller LE",
	 },
	trophytruck = {
	   category = "offroad",
	   brand = "Annis",
	   model = "trophytruck",
	   price = 6000,
	   name = "Trophy Truck",
	 },
	seven70 = {
	   category = "sports",
	   brand = "Dewbauchee",
	   model = "seven70",
	   price = 14000,
	   name = "Seven-70",
	 },
	blista3 = {
	   category = "compacts",
	   brand = "Dinka",
	   model = "blista3",
	   price = 1500,
	   name = "Blista Go Go Monkey",
	 },
	xa21 = {
	   category = "super",
	   brand = "Ocelot",
	   model = "xa21",
	   price = 18000,
	   name = "XA-21",
	 },
	buccaneer2 = {
	   category = "muscle",
	   brand = "Albany",
	   model = "buccaneer2",
	   price = 2450,
	   name = "Buccaneer Rider",
	 },
	visione = {
	   category = "sports",
	   brand = "Grotti",
	   model = "visione",
	   price = 75000,
	   name = "Visione",
	 },
	casco = {
	   category = "sportsclassics",
	   brand = "Lampadati",
	   model = "casco",
	   price = 10000,
	   name = "Casco",
	 },
	streiter = {
	   category = "sports",
	   brand = "Benefactor",
	   model = "streiter",
	   price = 4000,
	   name = "Streiter",
	 },
	lurcher = {
	   category = "muscle",
	   brand = "Bravado",
	   model = "lurcher",
	   price = 2100,
	   name = "Gauntlet Classic Custom",
	 },
	blade = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "blade",
	   price = 2350,
	   name = "Blade",
	 },
	cypher = {
	   category = "sports",
	   brand = "Ubermacht",
	   model = "cypher",
	   price = 15500,
	   name = "Cypher",
	 },
	elegy = {
	   category = "sports",
	   brand = "Annis",
	   model = "elegy",
	   price = 14500,
	   name = "Elegy Retro Custom",
	 },
	windsor2 = {
	   category = "coupes",
	   brand = "Enus",
	   model = "windsor2",
	   price = 3400,
	   name = "Windsor Drop",
	 },
	baller4 = {
	   category = "suvs",
	   brand = "Gallivanter",
	   model = "baller4",
	   price = 2900,
	   name = "Baller LE LWB",
	 },
	voltic2 = {
	   category = "super",
	   brand = "Coil",
	   model = "voltic2",
	   price = 983040,
	   name = "Rocket Voltic",
	 },
	asbo = {
	   category = "compacts",
	   brand = "Maxwell",
	   model = "asbo",
	   price = 400,
	   name = "Asbo",
	 },
	growler = {
	   category = "sports",
	   brand = "Pfister",
	   model = "growler",
	   price = 20500,
	   name = "Growler",
	 },
	penumbra2 = {
	   category = "sports",
	   brand = "Maibatsu",
	   model = "penumbra2",
	   price = 3000,
	   name = "Penumbra FF",
	 },
	hotknife = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "hotknife",
	   price = 9000,
	   name = "Hotknife",
	 },
	t20 = {
	   category = "super",
	   brand = "Progen",
	   model = "t20",
	   price = 165000,
	   name = "T20",
	 },
	carbonizzare = {
	   category = "sports",
	   brand = "Grotti",
	   model = "carbonizzare",
	   price = 15500,
	   name = "Carbonizzare",
	 },
	tezeract = {
	   category = "super",
	   brand = "Pegassi",
	   model = "tezeract",
	   price = 22000,
	   name = "Tezeract",
	 },
	bjxl = {
	   category = "suvs",
	   brand = "Karin",
	   model = "bjxl",
	   price = 1900,
	   name = "BeeJay XL",
	 },
	fq2 = {
	   category = "suvs",
	   brand = "Fathom",
	   model = "fq2",
	   price = 1850,
	   name = "FQ2",
	 },
	adder = {
	   category = "super",
	   brand = "Truffade",
	   model = "adder",
	   price = 28000,
	   name = "Adder",
	 },
	rocoto = {
	   category = "suvs",
	   brand = "Obey",
	   model = "rocoto",
	   price = 1300,
	   name = "Rocoto",
	 },
	seminole2 = {
	   category = "suvs",
	   brand = "Canis",
	   model = "seminole2",
	   price = 1300,
	   name = "Seminole Frontier",
	 },
	cheburek = {
	   category = "sportsclassic",
	   brand = "Rune",
	   model = "cheburek",
	   price = 700,
	   name = "Cheburek",
	 },
	emerus = {
	   category = "super",
	   brand = "Progen",
	   model = "emerus",
	   price = 22000,
	   name = "Emerus",
	 },
	moonbeam = {
	   category = "vans",
	   brand = "Declasse",
	   model = "moonbeam",
	   price = 1300,
	   name = "Moonbeam",
	 },
	zr350 = {
	   category = "sports",
	   brand = "Annis",
	   model = "zr350",
	   price = 3800,
	   name = "ZR350",
	 },
	stratum = {
	   category = "sedans",
	   brand = "Zirconium",
	   model = "stratum",
	   price = 1500,
	   name = "Stratum",
	 },
	issi7 = {
	   category = "compacts",
	   brand = "Weeny",
	   model = "issi7",
	   price = 10000,
	   name = "Issi Sport",
	 },
	rapidgt3 = {
	   category = "sportsclassics",
	   brand = "Dewbauchee",
	   model = "rapidgt3",
	   price = 9000,
	   name = "Rapid GT",
	 },
	italigtb = {
	   category = "super",
	   brand = "Progen",
	   model = "italigtb",
	   price = 17000,
	   name = "Itali GTB",
	 },
	felon2 = {
	   category = "coupes",
	   brand = "Lampadati",
	   model = "felon2",
	   price = 3700,
	   name = "Felon GT",
	 },
	sultanrs = {
	   category = "sports",
	   brand = "Karin",
	   model = "sultanrs",
	   price = 7650,
	   name = "Sultan RS",
	 },
	zion2 = {
	   category = "coupes",
	   brand = "Übermacht",
	   model = "zion2",
	   price = 2800,
	   name = "Zion Cabrio",
	 },
	brioso = {
	   category = "compacts",
	   brand = "Grotti",
	   model = "brioso",
	   price = 2000,
	   name = "Brioso R/A",
	 },
	panto = {
	   category = "compacts",
	   brand = "Benefactor",
	   model = "panto",
	   price = 320,
	   name = "Panto",
	 },
	monroe = {
	   category = "sportsclassics",
	   brand = "Pegassi",
	   model = "monroe",
	   price = 11500,
	   name = "Monroe",
	 },
	toreador = {
	   category = "sportsclassic",
	   brand = "Pegassi",
	   model = "toreador",
	   price = 5000,
	   name = "Toreador",
	 },
	pariah = {
	   category = "sports",
	   brand = "Ocelot",
	   model = "pariah",
	   price = 9000,
	   name = "Pariah",
	 },
	michelli = {
	   category = "sportsclassic",
	   brand = "Lampadati",
	   model = "michelli",
	   price = 3000,
	   name = "Michelli GT",
	 },
	chino = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "chino",
	   price = 500,
	   name = "Chino",
	 },
	tribike = {
	   price = 50,
	   model = "tribike",
	   name = "Tri Bike",
	   category = "cycles",
	 },
	slamvan3 = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "slamvan3",
	   price = 1700,
	   name = "Slam Van Custom",
	 },
	ruston = {
	   category = "sports",
	   brand = "Hijak",
	   model = "ruston",
	   price = 13000,
	   name = "Ruston",
	 },
	dune = {
	   category = "offroad",
	   brand = "Annis",
	   model = "dune",
	   price = 1400,
	   name = "Dune Buggy",
	 },
	turismo2 = {
	   category = "sportsclassic",
	   brand = "Grotti",
	   model = "turismo2",
	   price = 17000,
	   name = "Turismo Classic",
	 },
	vagrant = {
	   category = "offroad",
	   brand = "Maxwell",
	   model = "vagrant",
	   price = 5000,
	   name = "Vagrant",
	 },
	rancherxl = {
	   category = "offroad",
	   brand = "Declasse",
	   model = "rancherxl",
	   price = 2400,
	   name = "Rancher XL",
	 },
	schafter2 = {
	   category = "sedans",
	   brand = "Benefactor",
	   model = "schafter2",
	   price = 1600,
	   name = "Schafter",
	 },
	dilettante2 = {
	   category = "compacts",
	   brand = "Karin",
	   model = "dilettante2",
	   price = 1200,
	   name = "Dilettante Patrol",
	 },
	jester2 = {
	   category = "sports",
	   brand = "Dinka",
	   model = "jester2",
	   price = 21000,
	   name = "Jester Racecar",
	 },
	dubsta2 = {
	   category = "suvs",
	   brand = "Benefactor",
	   model = "dubsta2",
	   price = 1950,
	   name = "Dubsta Luxuary",
	 },
	sheava = {
	   category = "super",
	   brand = "Emperor",
	   model = "sheava",
	   price = 22000,
	   name = "ETR1",
	 },
	landstalker2 = {
	   category = "suvs",
	   brand = "Dundreary",
	   model = "landstalker2",
	   price = 2600,
	   name = "Landstalker XL",
	 },
	pigalle = {
	   category = "sportsclassics",
	   brand = "Lampadati",
	   model = "pigalle",
	   price = 9200,
	   name = "Pigalle",
	 },
	patriot = {
	   category = "suvs",
	   brand = "Mammoth",
	   model = "patriot",
	   price = 2100,
	   name = "Patriot",
	 },
	omnis = {
	   category = "sports",
	   brand = "Wow",
	   model = "omnis",
	   price = 9000,
	   name = "Omnis",
	 },
	deveste = {
	   category = "super",
	   brand = "Principe",
	   model = "deveste",
	   price = 23400,
	   name = "Deveste",
	 },
	dominator7 = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "dominator7",
	   price = 11000,
	   name = "Dominator ASP",
	 },
	chino2 = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "chino2",
	   price = 800,
	   name = "Chino Luxe",
	 },
	dominator = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "dominator",
	   price = 6250,
	   name = "Dominator",
	 },
	jb7002 = {
	   category = "sportsclassic",
	   brand = "Dewbauchee",
	   model = "jb7002",
	   price = 4000,
	   name = "JB 700W",
	 },
	granger = {
	   category = "suvs",
	   brand = "Declasse",
	   model = "granger",
	   price = 2200,
	   name = "Granger",
	 },
	verlierer2 = {
	   category = "sports",
	   brand = "Bravado",
	   model = "verlierer2",
	   price = 9050,
	   name = "Verlierer",
	 },
	tyrus = {
	   category = "super",
	   brand = "Progen",
	   model = "tyrus",
	   price = 23000,
	   name = "Tyrus",
	 },
	f620 = {
	   category = "coupes",
	   brand = "Ocelot",
	   model = "f620",
	   price = 3250,
	   name = "F620",
	 },
	tampa = {
	   category = "muscle",
	   brand = "Declasse",
	   model = "tampa",
	   price = 2450,
	   name = "Tampa",
	 },
	locust = {
	   category = "sports",
	   brand = "Ocelot",
	   model = "locust",
	   price = 20000,
	   name = "Locust",
	 },
	habanero = {
	   category = "suvs",
	   brand = "Emperor",
	   model = "habanero",
	   price = 2000,
	   name = "Habanero",
	 },
	stretch = {
	   category = "sedans",
	   brand = "Dundreary",
	   model = "stretch",
	   price = 1900,
	   name = "Stretch",
	 },
	remus = {
	   category = "sports",
	   brand = "Annis",
	   model = "remus",
	   price = 4800,
	   name = "Remus",
	 },
	virgo = {
	   category = "muscle",
	   brand = "Albany",
	   model = "virgo",
	   price = 2200,
	   name = "Virgo",
	 },
	prototipo = {
	   category = "super",
	   brand = "Grotti",
	   model = "prototipo",
	   price = 23500,
	   name = "X80 Proto",
	 },
	surfer = {
	   category = "vans",
	   brand = "BF",
	   model = "surfer",
	   price = 900,
	   name = "Surfer",
	 },
	verus = {
	   category = "offroad",
	   brand = "Dinka",
	   model = "verus",
	   price = 2000,
	   name = "Verus",
	 },
	burrito3 = {
	   category = "vans",
	   brand = "Declasse",
	   model = "burrito3",
	   price = 400,
	   name = "Burrito",
	 },
	banshee2 = {
	   category = "super",
	   brand = "Bravado",
	   model = "banshee2",
	   price = 12000,
	   name = "Banshee 900R",
	 },
	issi2 = {
	   category = "compacts",
	   brand = "Weeny",
	   model = "issi2",
	   price = 700,
	   name = "Issi",
	 },
	alpha = {
	   category = "sports",
	   brand = "Albany",
	   model = "alpha",
	   price = 5300,
	   name = "Alpha",
	 },
	virgo2 = {
	   category = "muscle",
	   brand = "Dundreary",
	   model = "virgo2",
	   price = 2100,
	   name = "Virgo Custom Classic",
	 },
	kalahari = {
	   category = "offroad",
	   brand = "Canis",
	   model = "kalahari",
	   price = 1400,
	   name = "Kalahari",
	 },
	club = {
	   category = "compacts",
	   brand = "BF",
	   model = "club",
	   price = 800,
	   name = "Club",
	 },
	tropos = {
	   category = "sports",
	   brand = "Lampadati",
	   model = "tropos",
	   price = 6500,
	   name = "Tropos Rallye",
	 },
	oracle = {
	   category = "sedans",
	   brand = "Ubermacht",
	   model = "oracle",
	   price = 2200,
	   name = "Oracle",
	 },
	hermes = {
	   category = "muscle",
	   brand = "Albany",
	   model = "hermes",
	   price = 53500,
	   name = "Hermes",
	 },
	torero = {
	   category = "sportsclassics",
	   brand = "Pegassi",
	   model = "torero",
	   price = 8400,
	   name = "Torero",
	 },
	manana = {
	   category = "muscle",
	   brand = "Albany",
	   model = "manana",
	   price = 1280,
	   name = "Manana",
	 },
	gt500 = {
	   category = "sportsclassics",
	   brand = "Grotti",
	   model = "gt500",
	   price = 13000,
	   name = "GT500",
	 },
	felon = {
	   category = "coupes",
	   brand = "Lampadati",
	   model = "felon",
	   price = 3100,
	   name = "Felon",
	 },
	stanier = {
	   category = "sedans",
	   brand = "Vapid",
	   model = "stanier",
	   price = 1900,
	   name = "Stanier",
	 },
	ztype = {
	   category = "sportsclassics",
	   brand = "Truffade",
	   model = "ztype",
	   price = 27000,
	   name = "Z-Type",
	 },
	gburrito2 = {
	   category = "vans",
	   brand = "Declasse",
	   model = "gburrito2",
	   price = 1150,
	   name = "Burrito Custom",
	 },
	entityxf = {
	   category = "super",
	   brand = "Överflöd",
	   model = "entityxf",
	   price = 18000,
	   name = "Entity XF",
	 },
	mamba = {
	   category = "sportsclassics",
	   brand = "Declasse",
	   model = "mamba",
	   price = 14000,
	   name = "Mamba",
	 },
	gresley = {
	   category = "suvs",
	   brand = "Bravado",
	   model = "gresley",
	   price = 2500,
	   name = "Gresley",
	 },
	huntley = {
	   category = "suvs",
	   brand = "Enus",
	   model = "huntley",
	   price = 2450,
	   name = "Huntley S",
	 },
	peyote = {
	   category = "sportsclassic",
	   brand = "Vapid",
	   model = "peyote",
	   price = 2350,
	   name = "Peyote",
	 },
	lynx = {
	   category = "sports",
	   brand = "Ocelot",
	   model = "lynx",
	   price = 15000,
	   name = "Lynx",
	 },
	feltzer3 = {
	   category = "sportsclassics",
	   brand = "Benefactor",
	   model = "feltzer3",
	   price = 11500,
	   name = "Stirling GT",
	 },
	schafter4 = {
	   category = "sports",
	   brand = "Benefactor",
	   model = "schafter4",
	   price = 2100,
	   name = "Schafter LWB",
	 },
	imorgon = {
	   category = "sports",
	   brand = "Overflod",
	   model = "imorgon",
	   price = 12000,
	   name = "Imorgon",
	 },
	ingot = {
	   category = "sedans",
	   brand = "Vulcar",
	   model = "ingot",
	   price = 4999,
	   name = "Ingot",
	 },
	novak = {
	   category = "suvs",
	   brand = "Lampadati",
	   model = "novak",
	   price = 7000,
	   name = "Novak",
	 },
	kuruma = {
	   category = "sports",
	   brand = "Karin",
	   model = "kuruma",
	   price = 7200,
	   name = "Kuruma",
	 },
	cheetah = {
	   category = "super",
	   brand = "Grotti",
	   model = "cheetah",
	   price = 21400,
	   name = "Cheetah",
	 },
	coquette4 = {
	   category = "sports",
	   brand = "Invetero",
	   model = "coquette4",
	   price = 22000,
	   name = "Coquette D10",
	 },
	comet6 = {
	   category = "sports",
	   brand = "Pfister",
	   model = "comet6",
	   price = 23000,
	   name = "Comet S2",
	 },
	infernus2 = {
	   category = "sportsclassics",
	   brand = "Pegassi",
	   model = "infernus2",
	   price = 24500,
	   name = "Infernus Classic",
	 },
	massacro = {
	   category = "sports",
	   brand = "Dewbauchee",
	   model = "massacro",
	   price = 11000,
	   name = "Massacro",
	 },
	previon = {
	   category = "coupes",
	   brand = "Karin",
	   model = "previon",
	   price = 14900,
	   name = "Previon",
	 },
	thrax = {
	   category = "super",
	   brand = "Truffade",
	   model = "thrax",
	   price = 18000,
	   name = "Thrax",
	 },
	jester3 = {
	   category = "sports",
	   brand = "Dinka",
	   model = "jester3",
	   price = 8500,
	   name = "Jester Classic",
	 },
	tulip = {
	   category = "muscle",
	   brand = "Declasse",
	   model = "tulip",
	   price = 8000,
	   name = "Tulip",
	 },
	swinger = {
	   category = "sportsclassic",
	   brand = "Ocelot",
	   model = "swinger",
	   price = 22100,
	   name = "Swinger",
	 },
	voodoo = {
	   category = "muscle",
	   brand = "Declasse",
	   model = "voodoo",
	   price = 1300,
	   name = "Voodoo",
	 },
	savestra = {
	   category = "sportsclassic",
	   brand = "Annis",
	   model = "savestra",
	   price = 6700,
	   name = "Savestra",
	 },
	s80 = {
	   category = "super",
	   brand = "Annis",
	   model = "s80",
	   price = 20500,
	   name = "S80RR",
	 },
	italigto = {
	   category = "sports",
	   brand = "Progen",
	   model = "italigto",
	   price = 26000,
	   name = "Itali GTO",
	 },
	dominator3 = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "dominator3",
	   price = 7000,
	   name = "Dominator GTX",
	 },
	tornado5 = {
	   category = "sportsclassic",
	   brand = "Declasse",
	   model = "tornado5",
	   price = 2200,
	   name = "Tornado Custom",
	 },
	rapidgt2 = {
	   category = "sports",
	   brand = "Dewbauchee",
	   model = "rapidgt2",
	   price = 9200,
	   name = "Rapid GT Convertible",
	 },
	guardian = {
	   category = "offroad",
	   brand = "Annis",
	   model = "guardian",
	   price = 2100,
	   name = "Guardian",
	 },
	comet3 = {
	   category = "sports",
	   brand = "Pfister",
	   model = "comet3",
	   price = 17500,
	   name = "Comet Retro Custom",
	 },
	ardent = {
	   category = "sportsclassics",
	   brand = "Ocelot",
	   model = "ardent",
	   price = 3000,
	   name = "Ardent",
	 },
	zion3 = {
	   category = "sportsclassic",
	   brand = "Übermacht",
	   model = "zion3",
	   price = 4500,
	   name = "Zion Classic",
	 },
	warrener2 = {
	   category = "sedans",
	   brand = "Vulcar",
	   model = "warrener2",
	   price = 3000,
	   name = "Warrener HKR",
	 },
	kamacho = {
	   category = "offroad",
	   brand = "Canis",
	   model = "kamacho",
	   price = 5000,
	   name = "Kamacho",
	 },
	nero = {
	   category = "super",
	   brand = "Truffade",
	   model = "nero",
	   price = 20000,
	   name = "Nero",
	 },
	sc1 = {
	   category = "super",
	   brand = "Übermacht",
	   model = "sc1",
	   price = 9000,
	   name = "SC1",
	 },
	fugitive = {
	   category = "sedans",
	   brand = "Cheval",
	   model = "fugitive",
	   price = 2000,
	   name = "Fugitive",
	 },
	deluxo = {
	   category = "sportsclassic",
	   brand = "Imponte",
	   model = "deluxo",
	   price = 5500,
	   name = "Deluxo",
	 },
	feltzer2 = {
	   category = "sports",
	   brand = "Benefactor",
	   model = "feltzer2",
	   price = 9700,
	   name = "Feltzer",
	 },
	superd = {
	   category = "sedans",
	   brand = "Enus",
	   model = "superd",
	   price = 1700,
	   name = "Super Diamond",
	 },
	sultan = {
	   category = "sports",
	   brand = "Karin",
	   model = "sultan",
	   price = 5000,
	   name = "Sultan",
	 },
	rt3000 = {
	   category = "sports",
	   brand = "Dinka",
	   model = "rt3000",
	   price = 6500,
	   name = "RT3000",
	 },
	asea = {
	   category = "sedans",
	   brand = "Declasse",
	   model = "asea",
	   price = 250,
	   name = "Asea",
	 },
	schwarzer = {
	   category = "sports",
	   brand = "Benefactor",
	   model = "schwarzer",
	   price = 4700,
	   name = "Schwartzer",
	 },
	penetrator = {
	   category = "super",
	   brand = "Ocelot",
	   model = "penetrator",
	   price = 13000,
	   name = "Penetrator",
	 },
	winky = {
	   category = "offroad",
	   brand = "Vapid",
	   model = "winky",
	   price = 1000,
	   name = "Winky",
	 },
	youga = {
	   category = "vans",
	   brand = "Bravado",
	   model = "youga",
	   price = 800,
	   name = "Youga",
	 },
	penumbra = {
	   category = "sports",
	   brand = "Maibatsu",
	   model = "penumbra",
	   price = 2200,
	   name = "Penumbra",
	 },
	primo = {
	   category = "sedans",
	   brand = "Albany",
	   model = "primo",
	   price = 500,
	   name = "Primo",
	 },
	blista2 = {
	   category = "compacts",
	   brand = "Dinka",
	   model = "blista2",
	   price = 1895,
	   name = "Blista Compact",
	 },
	fmj = {
	   category = "super",
	   brand = "Vapid",
	   model = "fmj",
	   price = 12500,
	   name = "FMJ",
	 },
	bobcatxl = {
	   category = "vans",
	   brand = "Vapid",
	   model = "bobcatxl",
	   price = 1350,
	   name = "Bobcat XL Open",
	 },
	bfinjection = {
	   category = "offroad",
	   brand = "Annis",
	   model = "bfinjection",
	   price = 900,
	   name = "Bf Injection",
	 },
	youga2 = {
	   category = "vans",
	   brand = "Bravado",
	   model = "youga2",
	   price = 1450,
	   name = "Youga Classic",
	 },
	outlaw = {
	   category = "offroad",
	   brand = "Nagasaki",
	   model = "outlaw",
	   price = 1500,
	   name = "Outlaw",
	 },
	futo = {
	   category = "coupes",
	   brand = "Karin",
	   model = "futo",
	   price = 1750,
	   name = "Futo",
	 },
	revolter = {
	   category = "sports",
	   brand = "Ubermacht",
	   model = "revolter",
	   price = 9500,
	   name = "Revolter",
	 },
	ellie = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "ellie",
	   price = 4225,
	   name = "Ellie",
	 },
	exemplar = {
	   category = "coupes",
	   brand = "Dewbauchee",
	   model = "exemplar",
	   price = 4000,
	   name = "Exemplar",
	 },
	primo2 = {
	   category = "sedans",
	   brand = "Albany",
	   model = "primo2",
	   price = 1450,
	   name = "Primo Custom",
	 },
	gauntlet4 = {
	   category = "muscle",
	   brand = "Bravado",
	   model = "gauntlet4",
	   price = 8000,
	   name = "Gauntlet Hellfire",
	 },
	rapidgt = {
	   category = "sports",
	   brand = "Dewbauchee",
	   model = "rapidgt",
	   price = 8600,
	   name = "Rapid GT",
	 },
	blazer2 = {
	   category = "offroad",
	   brand = "Nagasaki",
	   model = "blazer2",
	   price = 700,
	   name = "Blazer Lifeguard",
	 },
	gauntlet5 = {
	   category = "muscle",
	   brand = "Bravado",
	   model = "gauntlet5",
	   price = 12000,
	   name = "Gauntlet Classic Custom",
	 },
	glendale2 = {
	   category = "sedans",
	   brand = "Benefactor",
	   model = "glendale2",
	   price = 1200,
	   name = "Glendale",
	 },
	oppressor = {
	   category = "super",
	   brand = "Pegassi",
	   model = "oppressor",
	   price = 9999999,
	   name = "Oppressor",
	 },
	specter = {
	   category = "sports",
	   brand = "Dewbauchee",
	   model = "specter",
	   price = 16000,
	   name = "Specter",
	 },
	schafter3 = {
	   category = "sports",
	   brand = "Benefactor",
	   model = "schafter3",
	   price = 3500,
	   name = "Schafter V12",
	 },
	moonbeam2 = {
	   category = "vans",
	   brand = "Declasse",
	   model = "moonbeam2",
	   price = 1500,
	   name = "Moonbeam Custom",
	 },
	viseris = {
	   category = "sportsclassic",
	   brand = "Lampadati",
	   model = "viseris",
	   price = 21000,
	   name = "Viseris",
	 },
	tribike3 = {
	   price = 52,
	   model = "tribike3",
	   name = "Tri Bike 3",
	   category = "cycles",
	 },
	yosemite = {
	   category = "muscle",
	   brand = "Declasse",
	   model = "yosemite",
	   price = 1950,
	   name = "Yosemite",
	 },
	mesa = {
	   category = "offroad",
	   brand = "Canis",
	   model = "mesa",
	   price = 1200,
	   name = "Mesa",
	 },
	slamvan2 = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "slamvan2",
	   price = 9000,
	   name = "Lost Slam Van",
	 },
	baller6 = {
	   category = "suvs",
	   brand = "Gallivanter",
	   model = "baller6",
	   price = 8200,
	   name = "Baller LE LWB (Armored)",
	 },
	glendale = {
	   category = "sedans",
	   brand = "Benefactor",
	   model = "glendale",
	   price = 340,
	   name = "Glendale",
	 },
	komoda = {
	   category = "sports",
	   brand = "Lampadati",
	   model = "komoda",
	   price = 5500,
	   name = "Komoda",
	 },
	raptor = {
	   category = "sports",
	   brand = "BF",
	   model = "raptor",
	   price = 9000,
	   name = "Raptor",
	 },
	dynasty = {
	   category = "sportsclassic",
	   brand = "Weeny",
	   model = "dynasty",
	   price = 2500,
	   name = "Dynasty",
	 },
	vamos = {
	   category = "muscle",
	   brand = "Declasse",
	   model = "vamos",
	   price = 3000,
	   name = "Vamos",
	 },
	italirsx = {
	   category = "sports",
	   brand = "Progen",
	   model = "italirsx",
	   price = 26000,
	   name = "Itali RSX",
	 },
	blista = {
	   category = "compacts",
	   brand = "Dinka",
	   model = "blista",
	   price = 1300,
	   name = "Blista",
	 },
	gauntlet3 = {
	   category = "muscle",
	   brand = "Bravado",
	   model = "gauntlet3",
	   price = 7500,
	   name = "Classic Gauntlet",
	 },
	brawler = {
	   category = "offroad",
	   brand = "Annis",
	   model = "brawler",
	   price = 4000,
	   name = "Brawler",
	 },
	vigero = {
	   category = "muscle",
	   brand = "Declasse",
	   model = "vigero",
	   price = 3950,
	   name = "Vigero",
	 },
	dominator8 = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "dominator8",
	   price = 8000,
	   name = "Dominator GTT",
	 },
	regina = {
	   category = "sedans",
	   brand = "Dundreary",
	   model = "regina",
	   price = 700,
	   name = "Regina",
	 },
	rumpo = {
	   category = "vans",
	   brand = "Bravado",
	   model = "rumpo",
	   price = 900,
	   name = "Rumpo",
	 },
	sabregt = {
	   category = "muscle",
	   brand = "Declasse",
	   model = "sabregt",
	   price = 2300,
	   name = "Sabre Turbo",
	 },
	italigtb2 = {
	   category = "super",
	   brand = "Progen",
	   model = "italigtb2",
	   price = 25000,
	   name = "Itali GTB",
	 },
	weevil = {
	   category = "compacts",
	   brand = "BF",
	   model = "weevil",
	   price = 900,
	   name = "Weevil",
	 },
	dukes = {
	   category = "muscle",
	   brand = "Imponte",
	   model = "dukes",
	   price = 2350,
	   name = "Dukes",
	 },
	le7b = {
	   category = "super",
	   brand = "Annis",
	   model = "le7b",
	   price = 26000,
	   name = "RE-7B",
	 },
	kanjo = {
	   category = "compacts",
	   brand = "Dinka",
	   model = "kanjo",
	   price = 1200,
	   name = "Blista Kanjo",
	 },
	yosemite2 = {
	   category = "muscle",
	   brand = "Declasse",
	   model = "yosemite2",
	   price = 5500,
	   name = "Yosemite Drift",
	 },
	retinue = {
	   category = "sportsclassic",
	   brand = "Vapid",
	   model = "retinue",
	   price = 3200,
	   name = "Retinue",
	 },
	neon = {
	   category = "sports",
	   brand = "Pfister",
	   model = "neon",
	   price = 22000,
	   name = "Neon",
	 },
	cruiser = {
	   price = 51,
	   model = "cruiser",
	   name = "Cruiser",
	   category = "cycles",
	 },
	jugular = {
	   category = "sports",
	   brand = "Ocelot",
	   model = "jugular",
	   price = 8000,
	   name = "Jugular",
	 },
	osiris = {
	   category = "super",
	   brand = "Pegassi",
	   model = "osiris",
	   price = 22000,
	   name = "Osiris",
	 },
	vectre = {
	   category = "sports",
	   brand = "Emperor",
	   model = "vectre",
	   price = 8000,
	   name = "Emperor Vectre",
	 },
	serrano = {
	   category = "suvs",
	   brand = "Benefactor",
	   model = "serrano",
	   price = 4800,
	   name = "Serrano",
	 },
	minivan = {
	   category = "vans",
	   brand = "Vapid",
	   model = "minivan",
	   price = 700,
	   name = "Minivan",
	 },
	faction3 = {
	   category = "muscle",
	   brand = "Willard",
	   model = "faction3",
	   price = 3500,
	   name = "Faction Custom Donk",
	 },
	infernus = {
	   category = "super",
	   brand = "Pegassi",
	   model = "infernus",
	   price = 23500,
	   name = "Infernus",
	 },
	btype2 = {
	   category = "sportsclassics",
	   brand = "Albany",
	   model = "btype2",
	   price = 8700,
	   name = "Franken Stange",
	 },
	dukes3 = {
	   category = "muscle",
	   brand = "Imponte",
	   model = "dukes3",
	   price = 4500,
	   name = "Beater Dukes",
	 },
	landstalker = {
	   category = "suvs",
	   brand = "Dundreary",
	   model = "landstalker",
	   price = 1200,
	   name = "Landstalker",
	 },
	paradise = {
	   category = "vans",
	   brand = "Bravado",
	   model = "paradise",
	   price = 900,
	   name = "Paradise",
	 },
	stalion = {
	   category = "muscle",
	   brand = "Declasse",
	   model = "stalion",
	   price = 3300,
	   name = "Stallion",
	 },
	baller5 = {
	   category = "suvs",
	   brand = "Gallivanter",
	   model = "baller5",
	   price = 7800,
	   name = "Baller LE (Armored)",
	 },
	peyote3 = {
	   category = "sportsclassic",
	   brand = "Vapid",
	   model = "peyote3",
	   price = 4800,
	   name = "Peyote Custom",
	 },
	fagaloa = {
	   category = "sportsclassics",
	   brand = "Vulcar",
	   model = "fagaloa",
	   price = 1300,
	   name = "Fagaloa",
	 },
	bison = {
	   category = "vans",
	   brand = "Bravado",
	   model = "bison",
	   price = 1800,
	   name = "Bison",
	 },
	tornado2 = {
	   category = "sportsclassic",
	   brand = "Declasse",
	   model = "tornado2",
	   price = 2200,
	   name = "Tornado Gang",
	 },
	bestiagts = {
	   category = "sports",
	   brand = "Grotti",
	   model = "bestiagts",
	   price = 3700,
	   name = "Bestia GTS",
	 },
	retinue2 = {
	   category = "sportsclassic",
	   brand = "Vapid",
	   model = "retinue2",
	   price = 3800,
	   name = "Retinue MKII",
	 },
	btype = {
	   category = "sportsclassics",
	   brand = "Albany",
	   model = "btype",
	   price = 7500,
	   name = "Roosevelt",
	 },
	stinger = {
	   category = "sportsclassic",
	   brand = "Grotti",
	   model = "stinger",
	   price = 3950,
	   name = "Stinger",
	 },
	cognoscenti = {
	   category = "sedans",
	   brand = "Enus",
	   model = "cognoscenti",
	   price = 2250,
	   name = "Cognoscenti",
	 },
	brioso2 = {
	   category = "compacts",
	   brand = "Grotti",
	   model = "brioso2",
	   price = 1200,
	   name = "Brioso 300",
	 },
	tailgater = {
	   category = "sedans",
	   brand = "Obey",
	   model = "tailgater",
	   price = 2200,
	   name = "Tailgater",
	 },
	issi4 = {
	   category = "compacts",
	   brand = "Weeny",
	   model = "issi4",
	   price = 8000,
	   name = "Issi Arena",
	 },
	bmx = {
	   price = 16,
	   model = "bmx",
	   name = "BMX",
	   category = "cycles",
	 },
	manana2 = {
	   category = "muscle",
	   brand = "Albany",
	   model = "manana2",
	   price = 2400,
	   name = "Manana Custom",
	 },
	zorrusso = {
	   category = "super",
	   brand = "Pegassi",
	   model = "zorrusso",
	   price = 27700,
	   name = "Zorrusso",
	 },
	surge = {
	   category = "sedans",
	   brand = "Cheval",
	   model = "surge",
	   price = 2000,
	   name = "Surge",
	 },
	tribike2 = {
	   price = 70,
	   model = "tribike2",
	   name = "Tri Bike 2",
	   category = "cycles",
	 },
	gauntlet = {
	   category = "muscle",
	   brand = "Bravado",
	   model = "gauntlet",
	   price = 2850,
	   name = "Gauntlet",
	 },
	speedo4 = {
	   category = "vans",
	   brand = "Vapid",
	   model = "speedo4",
	   price = 1500,
	   name = "Speedo Custom",
	 },
	cog55 = {
	   category = "sedans",
	   brand = "Enus",
	   model = "cog55",
	   price = 2200,
	   name = "Cognoscenti 55",
	 },
	scorcher = {
	   price = 28,
	   model = "scorcher",
	   name = "Scorcher",
	   category = "cycles",
	 },
	entity2 = {
	   category = "super",
	   brand = "Överflöd",
	   model = "entity2",
	   price = 16400,
	   name = "Entity XXR",
	 },
	stromberg = {
	   category = "sportsclassic",
	   brand = "Ocelot",
	   model = "stromberg",
	   price = 8000,
	   name = "Stromberg",
	 },
	sultan3 = {
	   category = "sports",
	   brand = "Karin",
	   model = "sultan3",
	   price = 5600,
	   name = "Sultan Classic Custom",
	 },
	turismor = {
	   category = "super",
	   brand = "Grotti",
	   model = "turismor",
	   price = 14000,
	   name = "Turismo R",
	 },
	xls = {
	   category = "suvs",
	   brand = "Benefactor",
	   model = "xls",
	   price = 1700,
	   name = "XLS",
	 },
	caracara2 = {
	   category = "offroad",
	   brand = "Vapid",
	   model = "caracara2",
	   price = 8000,
	   name = "Caracara 4x4",
	 },
	blazer3 = {
	   category = "offroad",
	   brand = "Nagasaki",
	   model = "blazer3",
	   price = 700,
	   name = "Blazer Hot Rod",
	 },
	trophytruck2 = {
	   category = "offroad",
	   brand = "Annis",
	   model = "trophytruck2",
	   price = 8000,
	   name = "Trophy Truck Limited",
	 },
	hellion = {
	   category = "offroad",
	   brand = "Annis",
	   model = "hellion",
	   price = 3800,
	   name = "Hellion",
	 },
	buccaneer = {
	   category = "muscle",
	   brand = "Albany",
	   model = "buccaneer",
	   price = 2250,
	   name = "Buccaneer",
	 },
	jester = {
	   category = "sports",
	   brand = "Dinka",
	   model = "jester",
	   price = 13225,
	   name = "Jester",
	 },
	blazer5 = {
	   category = "offroad",
	   brand = "Nagasaki",
	   model = "blazer5",
	   price = 4000,
	   name = "Blazer Aqua",
	 },
	toros = {
	   category = "suvs",
	   brand = "Pegassi",
	   model = "toros",
	   price = 6500,
	   name = "Toros",
	 },
	emperor = {
	   category = "sedans",
	   brand = "Albany",
	   model = "emperor",
	   price = 425,
	   name = "Emperor",
	 },
	vagner = {
	   category = "super",
	   brand = "Dewbauchee",
	   model = "vagner",
	   price = 166000,
	   name = "Vagner",
	 },
	cavalcade = {
	   category = "suvs",
	   brand = "Albany",
	   model = "cavalcade",
	   price = 1400,
	   name = "Cavalcade",
	 },
	bifta = {
	   category = "offroad",
	   brand = "Annis",
	   model = "bifta",
	   price = 1550,
	   name = "Bifta",
	 },
	faction = {
	   category = "muscle",
	   brand = "Willard",
	   model = "faction",
	   price = 1700,
	   name = "Faction",
	 },
	comet4 = {
	   category = "sports",
	   brand = "Pfister",
	   model = "comet4",
	   price = 11000,
	   name = "Comet Safari",
	 },
	btype3 = {
	   category = "sportsclassics",
	   brand = "Albany",
	   model = "btype3",
	   price = 6300,
	   name = "Roosevelt Valor",
	 },
	hustler = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "hustler",
	   price = 9500,
	   name = "Hustler",
	 },
	massacro2 = {
	   category = "sports",
	   brand = "Dewbauchee",
	   model = "massacro2",
	   price = 8000,
	   name = "Massacro Racecar",
	 },
	cheetah2 = {
	   category = "sports",
	   brand = "Grotti",
	   model = "cheetah2",
	   price = 19500,
	   name = "Cheetah Classic",
	 },
	riata = {
	   category = "offroad",
	   brand = "Vapid",
	   model = "riata",
	   price = 38000,
	   name = "Riata",
	 },
	dominator4 = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "dominator4",
	   price = 20000,
	   name = "Dominator Arena",
	 },
	stafford = {
	   category = "sedans",
	   brand = "Enus",
	   model = "stafford",
	   price = 3000,
	   name = "Stafford",
	 },
	buffalo = {
	   category = "sports",
	   brand = "Bravado",
	   model = "buffalo",
	   price = 1875,
	   name = "Buffalo",
	 },
	surano = {
	   category = "sports",
	   brand = " Benefactor",
	   model = "surano",
	   price = 8000,
	   name = "Surano",
	 },
	gb200 = {
	   category = "sports",
	   brand = "Vapid",
	   model = "gb200",
	   price = 14000,
	   name = "GB 200",
	 },
	everon = {
	   category = "offroad",
	   brand = "Karin",
	   model = "everon",
	   price = 6000,
	   name = "Everon",
	 },
	dominator2 = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "dominator2",
	   price = 5000,
	   name = "Pißwasser Dominator",
	 },
	ruiner = {
	   category = "muscle",
	   brand = "Imponte",
	   model = "ruiner",
	   price = 2900,
	   name = "Ruiner",
	 },
	euros = {
	   category = "sports",
	   brand = "Annis",
	   model = "euros",
	   price = 8000,
	   name = "Euros",
	 },
	stalion2 = {
	   category = "muscle",
	   brand = "Declasse",
	   model = "stalion2",
	   price = 4000,
	   name = "Stallion Burgershot",
	 },
	futo2 = {
	   category = "sports",
	   brand = "Karin",
	   model = "futo2",
	   price = 3900,
	   name = "Futo GTX",
	 },
	nebula = {
	   category = "sportsclassic",
	   brand = "Vulcar",
	   model = "nebula",
	   price = 2200,
	   name = "Nebula",
	 },
	picador = {
	   category = "muscle",
	   brand = "Cheval",
	   model = "picador",
	   price = 2000,
	   name = "Picador",
	 },
	bullet = {
	   category = "super",
	   brand = "Vapid",
	   model = "bullet",
	   price = 12000,
	   name = "Bullet",
	 },
	rumpo3 = {
	   category = "vans",
	   brand = "Bravado",
	   model = "rumpo3",
	   price = 1950,
	   name = "Rumpo Custom",
	 },
	taipan = {
	   category = "super",
	   brand = "Cheval",
	   model = "taipan",
	   price = 185000,
	   name = "Taipan",
	 },
	nightshade = {
	   category = "muscle",
	   brand = "Imponte",
	   model = "nightshade",
	   price = 7000,
	   name = "Nightshade",
	 },
	deviant = {
	   category = "muscle",
	   brand = "Schyster",
	   model = "deviant",
	   price = 7000,
	   name = "Deviant",
	 },
	sentinel = {
	   category = "coupes",
	   brand = "Übermacht",
	   model = "sentinel",
	   price = 3000,
	   name = "Sentinel",
	 },
	yosemite3 = {
	   category = "offroad",
	   brand = "Declasse",
	   model = "yosemite3",
	   price = 42500,
	   name = "Yosemite Rancher",
	 },
	rebel2 = {
	   category = "offroad",
	   brand = "Annis",
	   model = "rebel2",
	   price = 2000,
	   name = "Rebel",
	 },
	elegy2 = {
	   category = "sports",
	   brand = "Annis",
	   model = "elegy2",
	   price = 15000,
	   name = "Elegy RH8",
	 },
	contender = {
	   category = "suvs",
	   brand = "Vapid",
	   model = "contender",
	   price = 3500,
	   name = "Contender",
	 },
	radi = {
	   category = "suvs",
	   brand = "Vapid",
	   model = "radi",
	   price = 1800,
	   name = "Radius",
	 },
	tailgater2 = {
	   category = "sedans",
	   brand = "Obey",
	   model = "tailgater2",
	   price = 5100,
	   name = "Tailgater S",
	 },
	tampa2 = {
	   category = "muscle",
	   brand = "Declasse",
	   model = "tampa2",
	   price = 8000,
	   name = "Drift Tampa",
	 },
	sabregt2 = {
	   category = "muscle",
	   brand = "Declasse",
	   model = "sabregt2",
	   price = 2650,
	   name = "Sabre GT",
	 },
	krieger = {
	   category = "super",
	   brand = "Benefactor",
	   model = "krieger",
	   price = 22200,
	   name = "Krieger",
	 },
	oracle2 = {
	   category = "coupes",
	   brand = "Übermacht",
	   model = "oracle2",
	   price = 2800,
	   name = "Oracle XS",
	 },
	freecrawler = {
	   category = "offroad",
	   brand = "Canis",
	   model = "freecrawler",
	   price = 2400,
	   name = "Freecrawler",
	 },
	clique = {
	   category = "muscle",
	   brand = "Vapid",
	   model = "clique",
	   price = 2000,
	   name = "Clique",
	 },
	asterope = {
	   category = "sedans",
	   brand = "Karin",
	   model = "asterope",
	   price = 1100,
	   name = "Asterope",
	 },
	intruder = {
	   category = "sedans",
	   brand = "Karin",
	   model = "intruder",
	   price = 1125,
	   name = "Intruder",
	 },
	seminole = {
	   category = "suvs",
	   brand = "Canis",
	   model = "seminole",
	   price = 2000,
	   name = "Seminole",
	 },
	comet5 = {
	   category = "sports",
	   brand = "Pfister",
	   model = "comet5",
	   price = 15500,
	   name = "Comet SR",
	 },
	reaper = {
	   category = "super",
	   brand = "Pegassi",
	   model = "reaper",
	   price = 10000,
	   name = "Reaper",
	 },
	rebla = {
	   category = "suvs",
	   brand = "Übermacht",
	   model = "rebla",
	   price = 2100,
	   name = "Rebla GTS",
	 },
	stingergt = {
	   category = "sportsclassics",
	   brand = "Grotti",
	   model = "stingergt",
	   price = 7000,
	   name = "Stinger GT",
	 },
	coquette2 = {
	   category = "sportsclassics",
	   brand = "Invetero",
	   model = "coquette2",
	   price = 16500,
	   name = "Coquette Classic",
	 },
	dubsta = {
	   category = "suvs",
	   brand = "Benefactor",
	   model = "dubsta",
	   price = 1900,
	   name = "Dubsta",
	 },
	sentinel3 = {
	   category = "coupes",
	   brand = "Übermacht",
	   model = "sentinel3",
	   price = 7000,
	   name = "Sentinel Classic",
	 },
	phoenix = {
	   category = "muscle",
	   brand = "Imponte",
	   model = "phoenix",
	   price = 6500,
	   name = "Phoenix",
	 },
	calico = {
	   category = "sports",
	   brand = "Karin",
	   model = "calico",
	   price = 3900,
	   name = "Calico GTF",
	 },
	issi3 = {
	   category = "compacts",
	   brand = "Weeny",
	   model = "issi3",
	   price = 500,
	   name = "Issi Classic",
	 },
	youga3 = {
	   category = "vans",
	   brand = "Bravado",
	   model = "youga3",
	   price = 1500,
	   name = "Youga Classic 4x4",
	 },
	blazer = {
	   price = 750,
	   model = "blazer",
	   name = "Blazer",
	   category = "offroad",
	 },
	pfister811 = {
	   category = "super",
	   brand = "Pfister",
	   model = "pfister811",
	   price = 22000,
	   name = "811",
	 },
	sugoi = {
	   category = "sports",
	   brand = "Dinka",
	   model = "sugoi",
	   price = 8500,
	   name = "Sugoi",
	 },
	gauntlet2 = {
	   category = "muscle",
	   brand = "Bravado",
	   model = "gauntlet2",
	   price = 7000,
	   name = "Redwood Gauntlet",
	 },
	ruiner2 = {
	   category = "muscle",
	   brand = "Imponte",
	   model = "ruiner2",
	   price = 5000,
	   name = "Ruiner 2000",
	 },
	windsor = {
	   category = "coupes",
	   brand = "Enus",
	   model = "windsor",
	   price = 2700,
	   name = "Windsor",
	 },
	premier = {
	   category = "sedans",
	   brand = "Declasse",
	   model = "premier",
	   price = 1200,
	   name = "Premier",
	 },
	furoregt = {
	   category = "sports",
	   brand = "Lampadati",
	   model = "furoregt",
	   price = 7800,
	   name = "Furore GT",
	 },
	banshee = {
	   category = "sports",
	   brand = "Bravado",
	   model = "banshee",
	   price = 5600,
	   name = "Banshee",
	 },
	gp1 = {
	   category = "super",
	   brand = "Progen",
	   model = "gp1",
	   price = 11000,
	   name = "GP1",
	 },
	fixter = {
	   price = 225,
	   model = "fixter",
	   name = "Fixter",
	   category = "cycles",
	 },
	drafter = {
	   category = "sports",
	   brand = "Obey",
	   model = "drafter",
	   price = 8000,
	   name = "8F Drafter",
	 },
	washington = {
	   category = "sedans",
	   brand = "Albany",
	   model = "washington",
	   price = 700,
	   name = "Washington",
	 },
	baller2 = {
	   category = "suvs",
	   brand = "Gallivanter",
	   model = "baller2",
	   price = 1500,
	   name = "Baller",
	 },
	autarch = {
	   category = "super",
	   brand = "Överflöd",
	   model = "autarch",
	   price = 22400,
	   name = "Autarch",
	 },
	furia = {
	   category = "super",
	   brand = "Grotti",
	   model = "furia",
	   price = 23000,
	   name = "Furia",
	 },
}